### ISSUE TITLE
NMDC API GUI documentation

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_documentation#26]
This issue is to track the work done on the API GUI documentation. See https://github.com/microbiomedata/NMDC_documentation/blob/api-gui-howto_guide/docs/howto_guides/api_gui.md for more details.

**Comment by brynnz22** [comment]
The first draft is complete. Currently getting feedback from @mslarae13 and @jkelliher-github.

**Comment by ssarrafan** [comment]
I will close this issue @brynnz22 since the first draft is done.

**Comment by mslarae13** [comment]
@brynnz22  since we closed this issue, for the draft, can we get additional issues for finalizing & publishing

**Comment by brynnz22** [comment]
Yes, I will create them!
