### ISSUE TITLE
Documentation issue - diataxis

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_documentation#3]
Re-format NMDC compiled documentation using diataxis framework

**Comment by ssarrafan** [comment]
Mid-sprint check update from Karen:
HI all, Since I was not able to stay in the mid-sprint meeting today, I wanted to give you an update. I am working with a LANL team member to reformat the documentation. She has completed the conversion of the LANL-generated ReadtheDocs to markdown. She will also be reformatting for the changes based on the diataxis framework. All of the current ReadtheDocs will be under the Reference section and we will be adding the other sections.  Here is a draft outline for the changes and a mock-up of what I think this should look like. We have many things in place that are appropriate to add with almost no changes. I think we will be reformatted and have all of these in place by the end of February. Many things are already created, but will need some modifications. I plan for these to be added by the April release.  Changing the documentation is an iterative process, and we will be adding more as we go.

**Comment by ssarrafan** [comment]
Moving this issue to the March sprint.  Plan completed in February. Work will continue through March.

**Comment by ssarrafan** [comment]
Moving documentation issue to April per @kwdavenport

**Comment by ssarrafan** [comment]
@kwdavenport any update on this GH issue?  Are you blocked on anything?  I am assuming we can close this after the release next week, correct?

**Comment by ssarrafan** [comment]
I'm closing this issue since the documentation was released yesterday

**Comment by kwdavenport** [comment]
We can close it after the release, but it will be ongoing (and never finished). We have the reformatting complete. We don't have all the new pieces in place, but much of it is there. The rest will be ongoing.

________________________________
From: ssarrafan ***@***.***>
Sent: Thursday, April 14, 2022 5:34 PM
To: microbiomedata/NMDC_documentation
Cc: Davenport, Karen Walston; Mention
Subject: [EXTERNAL] Re: [microbiomedata/NMDC_documentation] Documentation issue - diataxis (Issue #3)


@kwdavenport<https://urldefense.com/v3/__https://github.com/kwdavenport__;!!Bt8fGhp8LhKGRg!V08BOr6aRHGlImlyB17v7_hjn6SaxaJuqy4ZP8T1SsErlSBhrxF5iawuYOkwWWdw5KI$> any update on this GH issue? Are you blocked on anything? I am assuming we can close this after the release next week, correct?
