### ISSUE TITLE
Documentation issue - schema updates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_documentation#4]
Update schema definitions and pull directly

**Comment by ssarrafan** [comment]
Moving documentation issue to April per @kwdavenport

**Comment by mslarae13** [comment]
@turbomam  I also think this one should be assigned to you. Will the documentation update automatically as schema updates are compelted? Is there something that has to be done to make it happen?

Similarly we need documentation for the submission portal: how it's developed, maintained, description on components. 

I can generate the "user friendly" information for tutorials and how - to. but I expect the explanation information will come from you.

**Comment by ssarrafan** [comment]
I will re-assign to @turbomam

**Comment by turbomam** [comment]
> Similarly we need documentation for the submission portal: how it's developed, maintained, description on components.

@ssarrafan and @mslarae13:
- is there a separate issue for the submission portal?
- should I assume that you want documentation about the study submission and the sample submission? 
  - I think my involvement in the study submission has been limited to the display hints.

**Comment by ssarrafan** [comment]
> > Similarly we need documentation for the submission portal: how it's developed, maintained, description on components.
> 
> @ssarrafan and @mslarae13:
> 
> * is there a separate issue for the submission portal?
> * should I assume that you want documentation about the study submission and the sample submission?
>   
>   * I think my involvement in the study submission has been limited to the display hints.

Hi @turbomam it makes sense to me to start on the submission portal documentation but will defer to @kwdavenport. I'll go ahed and close this issue now the the release is out.
