### ISSUE TITLE
Streamlining documentation into one place and deciding on document hosting service

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/NMDC_documentation#42]
Make sure all the scripts to generate the docs are hosted in the NMDC_Documentation repo and make sure a service for hosting/ building the documents is democratically selected. 

Current todos:
[]add scripts to generating documents to NMDC_documentation
[]select service on hosting/building docs

**Comment by ssarrafan** [comment]
Shreyas said this was done at the last hackathon so closing this issue.
Will just be pointing to external repo.
