### ISSUE TITLE
Add the API documentation How to guide to the front facing documentation

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/NMDC_documentation#43]
I wrote some user-centered API documentation (https://github.com/microbiomedata/NMDC_documentation/blob/main/docs/howto_guides/api_gui.md) that would be nice to see in the front facing documentation

@kheal

**Comment by aclum** [comment]
I think this is done, the swagger ui documentation does appear to be pulling from the api_gui.md. @brynnz22  can this be closed?

**Comment by brynnz22** [comment]
Yep I'll close it. Thanks.
