### ISSUE TITLE
Documentation issue - MIxS update

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_documentation#5]
Update MIxS to use v6

**Comment by mslarae13** [comment]
Currently, from what I can tell, an instance of MIxS v5 was pulled and added to the schema. This should be removed. MIxS v6 read the docs should be pulled from MIxS instead of copying an instance.

@cmungall , @wdduncan  ... can you chime in if you agree with this / provide some context on what we need to do to accomplish this? 
Will this affect the portal .. or break anything else?

**Comment by wdduncan** [comment]
@mslarae13 Has MIXS 6 been released yet? I didn't think it had. 

Once it is released, our plan is to update the schema with the new version.

**Comment by ssarrafan** [comment]
Moving documentation issue to April per @kwdavenport

**Comment by mslarae13** [comment]
@turbomam I think this should be assigned to you? I have NO idea where the MIxS v6 documentation is, or how we will pull it in.

If you disagree, we should disucss soon to ensure the documentation gets completed for the April release.

**Comment by ssarrafan** [comment]
@turbomam I will re-assign to you.

**Comment by turbomam** [comment]
I'm going to start collecting some notes here. I don't mean to say that this is all the documentation I'll be providing!.

The mechanism for integrating MIxS terms, specifically those from 12 different packages, is briefly described in [nmdc-schema PR #292](https://github.com/microbiomedata/nmdc-schema/pull/292)

Especially see the quick and dirty code that does the integration, `util/reconsititute_mixs.py` and the resulting LinkML file, `src/schema/mixs_6_for_nmdc.yaml`

The process is started by examining all slots included by the previous, essentially static MIxS5 import, `../src/schema/mixs.yaml`, all slots assigned to the [NMDC `biosample` class](https://github.com/microbiomedata/nmdc-schema/blob/0c0db98b79220f8163d98b0773a7299e8a8646ea/src/schema/nmdc.yaml#L139-L291), and all classes assigned to the evolving NMDC DH schema, [for example here](https://raw.githubusercontent.com/microbiomedata/sheets_and_friends/issue-100-netlify-linkml-datastructure/artifacts/nmdc_dh.yaml).


I can include/check all slots for a MIMS sample, like the environmental section, etc. (but not the grouping slots themselves!)

section | core terms
-- | --
environment | 10
investigation | 6
nucleic acid sequence source | 25
sequencing | 57

like

- environment
  - alt
  - collection_date
  - depth
  - elev
  - env_broad_scale
  - env_local_scale
  - env_medium
  - geo_loc_name
  - lat_lon
  - temp
- investigation
  - samp_name
  - samp_taxon_id
  - project_name
  - experimental_factor
  - neg_cont_type
  - pos_cont_type

**Comment by turbomam** [comment]
Rough stream of consciousness draft: [Integration of MIxS into the NMDC schema: tech notes](https://docs.google.com/document/d/1Z9Pm6KQfqFvPvHzwl4658iivG9Guyt97syGu8u7t0og/edit#heading=h.my5n4mj8wjg2)

**Comment by ssarrafan** [comment]
@kwdavenport can we consider this issue closed?

**Comment by kwdavenport** [comment]
I don't think so. I'll be talking with Mark and Montana tomorrow. I am thinking it should go into the May sprint, but I can let you know after our meeting (at 8am PT).



________________________________
From: ssarrafan ***@***.***>
Sent: Thursday, April 28, 2022 3:54 PM
To: microbiomedata/NMDC_documentation
Cc: Davenport, Karen Walston; Mention
Subject: [EXTERNAL] Re: [microbiomedata/NMDC_documentation] Documentation issue - MIxS update (Issue #5)


@kwdavenport<https://urldefense.com/v3/__https://github.com/kwdavenport__;!!Bt8fGhp8LhKGRg!TsI9X1gsBEovJqXiPDvYgiuQgZuS3aQp9cUyeIzLbtni78F9UOhLlqF7ypC2qREu1MM$> can we consider this issue closed?

**Comment by ssarrafan** [comment]
I haven't heard back so I will move this to the May sprint @kwdavenport @turbomam

**Comment by turbomam** [comment]
How can we get the best, most automated integration between @sujaypatil96's https://microbiomedata.github.io/mixs and https://nmdc-docs-sphinx.readthedocs.io/en/latest/reference/metadata/combined_schema_docs.html#mixs-soil-package (for example), which is managed by @kwdavenport and Yan?

**Comment by turbomam** [comment]
https://github.com/cidgoh/DataHarmonizer/issues/313

**Comment by ssarrafan** [comment]
I'll move this to July then but let me know if you are not planning to work on it and I can move it to the backlog.  I'm not sure how high the priority for this is?  @cmungall @emileyfadrosh

**Comment by ssarrafan** [comment]
This issue has been in multiple sprints. I'm going to move it to the backlog. Let me know if it should be moved to the active sprint.  @turbomam @mslarae13

**Comment by ssarrafan** [comment]
@shreddd if we discuss documentation at SW Best Practices this is a good issue to refer to

**Comment by ssarrafan** [comment]
@turbomam @mslarae13 is this still needed?

**Comment by emileyfadrosh** [comment]
This looks quite old, so I am going to close out.

**Comment by mslarae13** [comment]
old or young... I am pretty sure NMDC is using the last "official" release of MIxS, and not v6. 
I think it's fine to close this one but we should decide how often NMDC is going to update its representation of  MIxS

**Comment by turbomam** [comment]
NMDC is using a ~ v6.0 fork of MIxS. Updating our import to GSC's v6.2 should be a high priority.

- https://github.com/microbiomedata/nmdc-schema/issues/1368

That change shouldn't be very difficult. I never finished because I wanted to get feedback on some design decisions related to slots the GSC retired or renamed between 6.0 on 6.2. Maybe I should just forget ahead and make a PR.
