### ISSUE TITLE
Documentation issue - Submission Portal / DH section readthedocs

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_documentation#6]
Generate data harmonizer read the docs.

**Comment by ssarrafan** [comment]
Moving documentation issue to April per @kwdavenport

**Comment by mslarae13** [comment]
We should make this issue specific to the April release and close it once the documentation is updated. There will be re-occuring issues for documentation updates.

**Comment by ssarrafan** [comment]
> We should make this issue specific to the April release and close it once the documentation is updated. There will be re-occuring issues for documentation updates.

Great! Happy to close now that the release is out.
