### ISSUE TITLE
Create documentation for NMDC high bandwidth transfer mechanism milestone

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/NMDC_documentation#66]

**Comment by aclum** [comment]
@shreddd do you have time to do this this sprint? Jeff was asking about this and there is currently no information about our globus endpoints.

**Comment by aclum** [comment]
can we close this based on this [existing documentation](https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/globus.html)?

**Comment by ssarrafan** [comment]
Discussed with Shreyas and this documentation is up to date, doesn't need to be updated. Closing this issue.
