### ISSUE TITLE
Develop the first version of the SOP to bring in external data into NMDC.

### ISSUE THREAD

**Issue by hubin-keio** [microbiomedata/NMDC_documentation#7]

**Comment by ssarrafan** [comment]
@hubin-keio I assume it's ok to close this issue since you have a first draft completed, correct?
https://docs.google.com/document/d/1LaW_9mbkWsjoAaPgBP5hHxX9t8bRBWtmHHeebNnhcq4/edit#heading=h.iq0q9pn82msy

**Comment by ssarrafan** [comment]
Haven't heard back so I'm closing this
@emileyfadrosh @hubin-keio
